### ISSUE TITLE
Can't get the poses_2d.tar.xz 

### ISSUE THREAD

**Issue by minhphuv** [GuillaumeRochette/PanopticProcessing#1]
Hi, thanks for your repo. I have some trouble running your code. Specifically, when I tried to run the list_openpose.sh, I notice that the second argument required the poses_2d.tar.xz file which is not available anywhere in your document. Could you help me bypass this problem? Many thanks

**Comment by GuillaumeRochette** [comment]
Hi,
I don't think you have followed the instructions correctly, I re-did step 4. and everything works fine, however maybe the instructions are not clear.
You need to follow the steps 1 to 3 and just replace the `/path/to/datasets` with the actual path you chose on your filesystem.
Regarding step 4, it generates the `list_openpose.sh` into the `OpenPose` repository that you have previously cloned. Then you change directory to that repository and finally execute the `list_openpose.sh` which will run `OpenPose` and generate the `<video_name>.tar.xz` files for you.

**Comment by minhphuv** [comment]
Thanks for your quick response. I followed your instruction and it generated the list_openpose.sh which contain the following
`bash OpenPose.docker.sh /Videos/00.mp4  /datasets/Panoptic/171026_pose1/Poses/2D/OpenPose/00.tar.xz
`
Then I checked the docker.sh file and the following line poses the error
`poses_tar=$(realpath $2)`
which results in the error of  "realpath: /datasets/Panoptic/171026_pose1/Poses/2D/OpenPose/00.tar.xz: No such file or directory"

Did I miss anything? Thank you.

**Comment by GuillaumeRochette** [comment]
Fixed it with the latest commit, the error would happen when the `poses_tar` parent directory did not exist previously.
